### PR TITLE
Build changes

### PR DESCRIPTION
**Pull request by PatrykMis**
* Remove AGP and DSL deprecations
* bump SDK versions
* Bump dependencies
* Full Gradle Wrapper upgrade

### CODE REVIEW

**Comment by SkewedZeppelin** [comment]
Thanks for this, I'll review and merge soon.

**Comment by SkewedZeppelin** [comment]
Merged manually, thanks!

**Comment by SkewedZeppelin** [comment]
Added to news and about/credits: https://divestos.org/index.php?page=news

**Comment by PatrykMis** [comment]
Merged, so closing this.

**Pull request closed without merging**
